const users=[
    {
        id:1,
        name:"danya",
        email:"wer@klu",
        type:"developer"
    },
    {
        id:2,
        name:"snehitha",
        email:"asdf@kl",
        type:"manager"
    },
    {
        id:3,
        name:"mona",
        email:"tyu@wer",
        type:"guest"
    },
    {
        id:4,
        name:"mohana",
        email:"ert@wer",
        type:"admin"
    },
    {
        id:5,
        name:"priya",
        email:"werty@wer",
        type:"client"
    }
];
module.exports=users;